appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice@sha256:49a71db4bf4cf0a4c0e789f3cb092950a53686087e619a8ad6b02c679ba135e3
appVersion: v0.8.0
appReplicas: 2
containerPort: 7070
containerEnvVars:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"  

serviceType: ClusterIP
servicePort: 7070