appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo/paymentservice@sha256:2bb8061c4c31b3762eb4d9effd64b9a31abbb92b37e44f66a79615bfe5890c22
appVersion: v0.8.0
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"

serviceType: ClusterIP
servicePort: 50051
